# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: def.proto for package ''

require 'grpc'
require './def_pb'

module UnaryService
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'UnaryService'

    rpc :echo, ::Request, ::Response
  end

  Stub = Service.rpc_stub_class
end

module StreamService
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'StreamService'

    rpc :serverStreamEcho, ::Request, stream(::Response)
    rpc :clientStreamEcho, stream(::Request), ::Response
  end

  Stub = Service.rpc_stub_class
end
