# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: def.proto

require 'google/protobuf'

descriptor_data = "\n\tdef.proto\"\x07\n\x05\x45mpty\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t2-\n\x0cUnaryService\x12\x1d\n\x04\x65\x63ho\x12\x08.Request\x1a\t.Response\"\x00\x32i\n\rStreamService\x12+\n\x10serverStreamEcho\x12\x08.Request\x1a\t.Response\"\x00\x30\x01\x12+\n\x10\x63lientStreamEcho\x12\x08.Request\x1a\t.Response\"\x00(\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('Empty').msgclass
Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('Request').msgclass
Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('Response').msgclass
